### ISSUE TITLE
Slides cannot be projected

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#278]
Every time I project the CLOS, I get the infamous
```
Error: calculating key projection/16/content: fetching projection 16 from datastore: fetching data: getOrSet for keys `[projection/16/id projection/16/type projection/16/content_object_id projection/16/meeting_id projection/16/options]`: waiting for key projection/16/options: waiting for value: context deadline exceeded
```

**Comment by ostcar** [comment]
@FinnStutzenstein could you test again after the fix from @r-peschke in #281 ?

**Comment by FinnStutzenstein** [comment]
This is not fixed. I get a very similar error (`type` instead of the field `options`):
```
Error: calculating key projection/39/content: fetching projection 39 from datastore: fetching object projection/39: fetching data: getOrSet for keys `[projection/39/id projection/39/type projection/39/content_object_id projection/39/meeting_id projection/39/options]`: waiting for key projection/39/type: waiting for value: context deadline exceeded
```
This is the datastore content for the projections:
```
{"id":39,"stable":false,"options":{},"meeting_id":1,"content_object_id":"topic/1","current_projector_id":1}
```

**Comment by FinnStutzenstein** [comment]
Also note, that it does not only appears for the CLOS slide; as you can see this is a topic slide. I also get the error for mediafile slides and more.

**Comment by r-peschke** [comment]
@FinnStutzenstein  I assume that this is the error from log, not the client response.
The error signals a timeout (deadlineExceeded), which is set exclusively for calculated fields to 1 second. 
Debugging the code I can reproduce the error.
With [PR282](https://github.com/OpenSlides/openslides-autoupdate-service/pull/282) I increased the time to 3 seconds and the response contains the timed- out part in the message.

With `git fetch origin pull/282/head:PR282_branch` you could create a branch and test it locally without being merged.

**Comment by FinnStutzenstein** [comment]
I used your branch, but it does not help. There is still an error.

**Comment by FinnStutzenstein** [comment]
To reproduce:
- start the setup in the main repo: `make run-dev`
- open the client
- go the the default committee and create a new meeting
- go into the meeting->agenda. Create a new agenda item
- go to the agenda list and project the item on the default projector
- open the default projector -> error

**Comment by ostcar** [comment]
There was a bug in the topic slide. I fixed it with #284. Afterwards I could not reproduce the error in the way you described.

Could you check if it is still possible to get the bug in other ways?

Maybe other slides are broken as well. In the topic slide the code expected, that each agenda_item has a number. Maybe other slides have the same assumption. @r-peschke could you check that?

**Comment by r-peschke** [comment]
Timeout error is still exists.
To reproduce:

1. openslides-autoupdat-service on commit b662b0110446e23706f6a9aa6a4c435d7b934f3f (HEAD -> master, origin/master, origin/HEAD)
2. start the setup in the main repo: make run-dev
3. open the client
4. go the the default committee and create a new meeting
5. go into the meeting and open the agenda list
6. create 2 simple topics
7. Use a second tab or tab in browser copy, now referred to as tab2.
8. tab2: open the meeting and choose projector
9. tab2:  Press F12 to see the console. You may disable all objects except errors.
8. tab1: click on the camera symbol left side of your topic/1. Click project in the popup window
9. tab2: You should see topic/1 in the projector.
10. tab1: click on the camera symbol symbol left of your topic/2 and click project in the popup window 
11. tab2: you should see topic/2 in the projector
12. Repeat steps 8-11, i.e. toggle between the 2 topics. After 1 and 5 times you will see
   - sometimes the topics highlighted in tab1 and shown in tab2 are not the same
   - tab2: sometimes you also see in the console the timeout error twice:   `slide error: calculating key projection/62/content timed out`
   - tab2: sometimes the projection is empty
   - sometimes it is correct

**Comment by ostcar** [comment]
Every time this happens, there should be an error message on the console. Could you paste them? Is this always the same error or is it different? Maybe you can paste many examples of the error message?

**Comment by ostcar** [comment]
> Every time this happens, there should be an error message on the console. Could you paste them? Is this always the same error or is it different? Maybe you can paste many examples of the error message?

I got it
